name: Initialize Terraform backend

on:
  workflow_dispatch:

jobs:
  TF-Init:
    runs-on: ubuntu-latest
    environment: dev
    env:
      TF_BACKEND_SA: ${{ vars.TF_BACKEND_SA }}
      TF_BACKEND_CONTAINER: ${{ vars.TF_BACKEND_CONTAINER }}
      TF_BACKEND_RESOURCE_GROUP: ${{ vars.TF_BACKEND_RG }}
      TF_BACKEND_SUBSCRIPTION_ID: ${{ secrets.TF_BACKEND_SUBSCRIPTION_ID }}
      TF_BACKEND_CONFIG_KEY: ${{ vars.TF_BACKEND_KEY }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SP_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_SP_TENANT_ID }}
    

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          
      - name: Initialize Terraform
        run: terraform init -backend-config=storage_account_name="$TF_BACKEND_SA" -backend-config=container_name="$TF_BACKEND_CONTAINER" -backend-config=key="$TF_BACKEND_CONFIG_KEY" -backend-config=resource_group_name="$TF_BACKEND_RESOURCE_GROUP"
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check --recursive ./